Exercises on Linear Algebra

In [2]:
import numpy as np

#1. Vector Operations
v1 = np.array([4,5,6])
v2 = np.array([1,2,3])

print(v1+v2)#Add the two vectors.
print(3*v1)#Multiply v1 by a scalar 3.
print(np.dot(v1,v2))#Compute the dot product of v1 and v2.

[5 7 9]
[12 15 18]
32


In [12]:
#2. Matrix Operations

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
print("Add matrices A and B:\n",a+b) #Add matrices A and B
print("A Before Transpose:\n",a)
print("Compute the transpose of matrix A:\n",np.transpose(a))#Compute the transpose of matrix A.
print("Multiply matrix A by a scalar 2:\n",2*a)#Multiply matrix A by a scalar 2.

Add matrices A and B:
 [[ 8 10 12]
 [14 16 18]]
A Before Transpose:
 [[1 2 3]
 [4 5 6]]
Compute the transpose of matrix A:
 [[1 4]
 [2 5]
 [3 6]]
Multiply matrix A by a scalar 2:
 [[ 2  4  6]
 [ 8 10 12]]


Exercise: Compute the Determinant 

In [18]:
#Problem 1: Determinant of a 2×2 Matrix

A = np.array([[5,-2],[3,1]])
print("det of A:",np.linalg.det(A))#Computing det(A)

#Problem 2: Determinant of a 3×3 Matrix

B = np.array([[2,4,3],[1,5,7],[6,8,9]])
print("det of B:",np.linalg.det(B))#Computing det(B)

det of A: 11.000000000000002
det of B: 44.000000000000014


Exercise: Matrix Inverse

In [4]:
#Problem 1:

A = np.array([[2,5],[3,1]])
B = np.linalg.det(A)
if np.isclose(B,0):
    print("A is NOT  invertible")
else:
    A_in = np.linalg.inv(A)
    print("A inverse is:\n", A_in)
    print("identity matrix:\n", A @ A_in)

A inverse is:
 [[-0.07692308  0.38461538]
 [ 0.23076923 -0.15384615]]
identity matrix:
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00  1.00000000e+00]]


📌 Exercises: Eigenvalues and Eigenvectors

In [11]:
#📝 Problem 1: Find the Eigenvalues and Eigenvectors of a 2×2 Matrix
A = np.array([[3,-1],[2,4]])
eigen_values,eigen_vectors = np.linalg.eig(A)
print("eigen values of A are:\n",eigen_values)
print("eigen vectors of A are:\n",eigen_vectors)
print("eigen values and eigen vectors of A are:\n",np.linalg.eig(A))
print("\n")

#📝 Problem 2: Eigenvalues of a Singular Matrix
B = np.array([[1,2],[2,4]])
eigen_values,eigen_vectors = np.linalg.eig(B)
print("eigen values of B are:\n",eigen_values)
print("eigen vectors of B are:\n",eigen_vectors)
print("eigen values and eigen vectors of B are:\n",np.linalg.eig(B))
print("\n")

#📝 Problem 3: Eigenvalues and Eigenvectors of a 3×3 Matrix
C = np.array([[6,2,1],[0,3,-1],[2,4,3]])
eigen_values,eigen_vectors = np.linalg.eig(C)
print("eigen values of C are:\n",eigen_values)
print("eigen vectors of C are:\n",eigen_vectors)
print("eigen values and eigen vectors of C are:\n",np.linalg.eig(C))
print("\n")

eigen values of A are:
 [3.5+1.32287566j 3.5-1.32287566j]
eigen vectors of A are:
 [[ 0.20412415-0.54006172j  0.20412415+0.54006172j]
 [-0.81649658+0.j         -0.81649658-0.j        ]]
eigen values and eigen vectors of A are:
 EigResult(eigenvalues=array([3.5+1.32287566j, 3.5-1.32287566j]), eigenvectors=array([[ 0.20412415-0.54006172j,  0.20412415+0.54006172j],
       [-0.81649658+0.j        , -0.81649658-0.j        ]]))


eigen values of B are:
 [0. 5.]
eigen vectors of B are:
 [[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]
eigen values and eigen vectors of B are:
 EigResult(eigenvalues=array([0., 5.]), eigenvectors=array([[-0.89442719, -0.4472136 ],
       [ 0.4472136 , -0.89442719]]))


eigen values of C are:
 [6.16631275+0.j       2.91684363+1.587351j 2.91684363-1.587351j]
eigen vectors of C are:
 [[-0.9038059 +0.j         -0.08434359-0.36346603j -0.08434359+0.36346603j]
 [ 0.12888005+0.j          0.02584611+0.49336987j  0.02584611-0.49336987j]
 [-0.40807454+0.j          0