Exercises on Linear Algebra

In [3]:
import numpy as np

#1. Vector Operations
v1 = np.array([4,5,6])
v2 = np.array([1,2,3])

print(v1+v2)#Add the two vectors.
print(3*v1)#Multiply v1 by a scalar 3.
print(np.dot(v1,v2))#Compute the dot product of v1 and v2.

[5 7 9]
[12 15 18]
32


In [12]:
#2. Matrix Operations

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
print("Add matrices A and B:\n",a+b) #Add matrices A and B
print("A Before Transpose:\n",a)
print("Compute the transpose of matrix A:\n",np.transpose(a))#Compute the transpose of matrix A.
print("Multiply matrix A by a scalar 2:\n",2*a)#Multiply matrix A by a scalar 2.

Add matrices A and B:
 [[ 8 10 12]
 [14 16 18]]
A Before Transpose:
 [[1 2 3]
 [4 5 6]]
Compute the transpose of matrix A:
 [[1 4]
 [2 5]
 [3 6]]
Multiply matrix A by a scalar 2:
 [[ 2  4  6]
 [ 8 10 12]]
