1️⃣ Creating Arrays

In [3]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
print("1D array:",arr1)

arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print("2D array:",arr2)

arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("3D array:",arr3)



1D array: [1 2 3 4 5]
2D array: [[1 2 3 4]
 [5 6 7 8]]
3D array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


2️⃣ Array Properties in NumPy

In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape of Array:", arr.shape)
print("size of array:",arr.size)
print("data type of array:",arr.dtype)
print("number of dimensions of array:",arr.ndim)
print("size of Each item:",arr.itemsize,"bytes")

Shape of Array: (2, 3)
size of array: 6
data type of array: int64
number of dimensions of array: 2
size of Each item: 8 bytes


3️⃣ Array Initialization in NumPy

In [22]:
zeroes_1d = np.zeros(5,dtype=float)
print("\n1D Array of Zeros:\n", zeroes_1d)

zeroes_2d = np.zeros((2,3),dtype=int)
print("\n2D Array of Zeros:\n", zeroes_2d)

ones_1d = np.ones(10,dtype=int)
print("\n1D Array of ones:\n", ones_1d)

ones_3d = np.ones((3,4,5),dtype=float)
print("\n3D Array of ones:\n", ones_3d)

empty = np.empty((2, 3),dtype=int)
print("Empty Array:\n", empty)

full = np.full((2,2),4,dtype=str)
print("full type Array:\n", full)

identity = np.eye(3,dtype=int)
print("identity type Array:\n", identity)



1D Array of Zeros:
 [0. 0. 0. 0. 0.]

2D Array of Zeros:
 [[0 0 0]
 [0 0 0]]

1D Array of ones:
 [1 1 1 1 1 1 1 1 1 1]

3D Array of ones:
 [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
Empty Array:
 [[0 0 0]
 [0 0 0]]
full type Array:
 [['4' '4']
 ['4' '4']]
identity type Array:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
