1️⃣ Creating Arrays

In [5]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
print("1D array:",arr1)

arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print("2D array:",arr2)

arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("3D array:",arr3)



1D array: [1 2 3 4 5]
2D array: [[1 2 3 4]
 [5 6 7 8]]
3D array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


2️⃣ Array Properties in NumPy

In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape of Array:", arr.shape)
print("size of array:",arr.size)
print("data type of array:",arr.dtype)
print("number of dimensions of array:",arr.ndim)
print("size of Each item:",arr.itemsize,"bytes")

Shape of Array: (2, 3)
size of array: 6
data type of array: int64
number of dimensions of array: 2
size of Each item: 8 bytes


3️⃣ Array Initialization in NumPy

In [22]:
zeroes_1d = np.zeros(5,dtype=float)
print("\n1D Array of Zeros:\n", zeroes_1d)

zeroes_2d = np.zeros((2,3),dtype=int)
print("\n2D Array of Zeros:\n", zeroes_2d)

ones_1d = np.ones(10,dtype=int)
print("\n1D Array of ones:\n", ones_1d)

ones_3d = np.ones((3,4,5),dtype=float)
print("\n3D Array of ones:\n", ones_3d)

empty = np.empty((2, 3),dtype=int)
print("Empty Array:\n", empty)

full = np.full((2,2),4,dtype=str)
print("full type Array:\n", full)

identity = np.eye(3,dtype=int)
print("identity type Array:\n", identity)



1D Array of Zeros:
 [0. 0. 0. 0. 0.]

2D Array of Zeros:
 [[0 0 0]
 [0 0 0]]

1D Array of ones:
 [1 1 1 1 1 1 1 1 1 1]

3D Array of ones:
 [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
Empty Array:
 [[0 0 0]
 [0 0 0]]
full type Array:
 [['4' '4']
 ['4' '4']]
identity type Array:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


In [8]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(arr[0:4,0:1])
print(arr[3:4,1:4])
print(arr[0:3,3:4])
print(arr.shape)

[[ 1]
 [ 5]
 [ 9]
 [13]]
[[14 15 16]]
[[ 4]
 [ 8]
 [12]]
(4, 4)


4️⃣ Array Indexing and Slicing in NumPy

In [19]:
#Accessing Elements in 2D Array
arr2 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(arr2[0,1])# Row 0, Column 1
print("Element at (2, 2):", arr2[2, 2])  # Row 2, Column 2

# Accessing Entire Row or Column
print(arr2[1,:])
print(arr2[:,2])

#📚 Slicing
#Slicing 2D Array
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
print("Top-left 2x2 slice:\n", arr2[0:2, 0:2])
print("Botttom-right 2x2 slice:\n", arr2[1:3, 1:3])

#1️⃣ Boolean Indexing
arr = np.array([10, 20, 30, 40, 50])
print("Elements greater than 25:",arr[arr>25])

#2️⃣ Fancy Indexing
indices = [0, 2, 4]
print("Selected elements:", arr[indices])

2
Element at (2, 2): 9
[4 5 6]
[3 6 9]
Top-left 2x2 slice:
 [[1 2]
 [4 5]]
Botttom-right 2x2 slice:
 [[5 6]
 [8 9]]
Elements greater than 25: [30 40 50]
Selected elements: [10 30 50]
